#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Set UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

source $HOME/.custom
if [ -f $HOME/.evp_custom ]; then
    source $HOME/.evp_custom
fi

export MAVEN_OPTS="-Xms256m -Xmx1024m -XX:MaxPermSize=512m"
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

